name: frontend_CICD

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Debug Workspace Contents
      run: ls -R  

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Build frontend
      run: npm run build --if-present

    - name: SonarQube frontend Scan
      uses: sonarsource/sonarqube-scan-action@master
      with:
        args: >
          -Dproject.settings=sonar-project.properties
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    - name: Check Quality Gate
      uses: sonarsource/sonarqube-quality-gate-action@master
      if: always()
      timeout-minutes: 5
      with:
        scanTaskId: ${{ steps.sonarqube.outputs.scanTaskId }}
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Upload to S3
      run: aws s3 sync . s3://${{ secrets.AWS_S3_BUCKET }} --delete
      
    - name: Debug AWS CodeDeploy
      run: |
        echo "List CodeDeploy applications:"
        aws deploy list-applications
        echo "List deployment groups for application 'webapp':"
        aws deploy list-deployment-groups --application-name webapp
      
    - name: Deploying to EC2
      run: aws deploy create-deployment --application-name webapp --deployment-group-name CodeDeployWebapp --github-location repository=${{ github.repository }},commitId=${{ github.sha }} --ignore-application-stop-failures
